import "unknwn.idl";
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(518B234D-1A13-4B6C-806B-7B191D4EEE59),
	helpstring("ICallBack 接口"),
	pointer_default(unique)
]
interface ICallBack : IUnknown
{
	[helpstring("方法SendMsgToClinet")]
	HRESULT SendMsgToClinet([in] long port) = 0;
};

[
	object,
	uuid(7799FC42-7048-4FDD-8035-DC1872A9F95E),
	helpstring("IComInterface 接口"),
	pointer_default(unique)
]
interface IComInterface : IUnknown
{
	[helpstring("方法Write")]
	HRESULT  Write([in] long size) = 0;

	[helpstring("方法Read")]
	HRESULT  Read([out] long* port) = 0;

	[helpstring("方法SetCallBack")]
	HRESULT  SetCallBack([in]ICallBack* pCallBack, [out]long* callBackID) = 0;

	[helpstring("方法ReleaseCallBack")]
	HRESULT  ReleaseCallBack([in]long callBackID) = 0;

	[helpstring("方法Test")]
	HRESULT  Test(void) = 0;
};

[
	uuid(2A312AA5-7142-492E-BBA0-39E144BA376E),
	version(1.0),
	helpstring("IComInterfaceLib 1.0 类型库")
]
library IComInterfaceLib
{
	importlib("stdole2.tlb");
	[
		uuid(99A87CC9-720F-4D8E-9E21-293019BA07F0),
		helpstring("IComInterfaceLib Class")
	]
	coclass CComInterface
	{
		[default] interface IComInterface;
	};
};
